version: '2'
services:
    edimca-app:
        image: edimca
        environment:
            - _JAVA_OPTIONS=-Xmx512m -Xms256m
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:postgresql://edimca-postgresql:5432/edimca
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    edimca-postgresql:
        extends:
            file: postgresql.yml
            service: edimca-postgresql
